-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 10, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6906_QUAL_PLAN" USING 'GCG_6906_QUAL_PLAN.mkd' PAGESIZE=4096 (
 "ROUTER" VARCHAR(20),
 "SEQUENCE" CHAR(6),
 "KEY_SEQUENCE" IDENTITY DEFAULT '0' CONSTRAINT "UK_KEY_SEQUENCE" UNIQUE USING 0,
 "DIMENSION" CHAR(40),
 "FREQUENCY" NUMERIC(7,2),
 "METHOD" CHAR(40),
 "PASS_FAIL" BIT NOT NULL,
 "PROCESS_DIM" NUMERIC(8,3),
 "PROCESS_DIM_DESC" CHAR(40),
 "UOM" CHAR(2),
 "CRITERIA_MIN" NUMERIC(7,3),
 "CRITERIA_MAX" NUMERIC(7,3),
 "PRIORITY" CHAR(3) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
